In [6]:
#1. Create a null vector of size 10 but the fifth value which is 1.
#sol
import numpy as np 
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [7]:
#2. Create a vector with values ranging from 10 to 49.
#sol
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
#3. Create a 3x3 matrix with values ranging from 0 to 8.
#sol
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0].
#sol
x=np.array([1,2,0,0,4,0])
print("indices of non-zero elements are:",np.nonzero(x))

indices of non-zero elements are: (array([0, 1, 4], dtype=int64),)


In [10]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
#sol
import random
random.seed(10)
x=np.random.random(size=(10,10))
print("Minimum vales:",x.min())
print("Maximum values:",x.max())
print(x)

Minimum vales: 0.010584185813584779
Maximum values: 0.9996712836470161
[[0.92919994 0.41735579 0.32257429 0.57526205 0.0149394  0.89381767
  0.23488565 0.84453253 0.31809837 0.04012427]
 [0.84261643 0.02855135 0.58380884 0.13461434 0.81051222 0.96463816
  0.89114    0.26269632 0.50858951 0.4487015 ]
 [0.81671709 0.21564071 0.04816891 0.76372181 0.01058419 0.50685009
  0.72365062 0.06868867 0.84953833 0.60020097]
 [0.83450878 0.65156825 0.88763584 0.55319116 0.13642037 0.30055929
  0.04211598 0.17836845 0.93190915 0.85794422]
 [0.38836734 0.30210863 0.06279828 0.99100053 0.97203013 0.39053727
  0.16207211 0.95737843 0.91033238 0.8757231 ]
 [0.55588726 0.54633574 0.3806821  0.60671713 0.69359138 0.35183242
  0.26677871 0.17469285 0.31989039 0.55969924]
 [0.16224457 0.85038718 0.62740931 0.78493493 0.71462958 0.40883527
  0.9239681  0.19450794 0.32494732 0.52010508]
 [0.98434237 0.45627297 0.72903432 0.18638342 0.88810646 0.46887127
  0.44109218 0.99967128 0.81439399 0.50845074]
 [0.80779

In [11]:
#6. Create a random vector of size 30 and find the mean value
#sol
arr=np.random.random((5,6))
Mean_value_of_the_matrix=np.mean(arr)
print("mean:",Mean_value_of_the_matrix)

mean: 0.5854136699119754
